### PR TITLE
Added rocketchat ids for all relevant entites

### PR DESCRIPTION
**Pull request by mmcdermott**

### CODE REVIEW

**Comment by tompollard** [comment]
GitHub doesn't handle diffs on CSVs well, so it would be easier if everyone included a summary of the changes in the description and checked that changes were being made to the top of branches as far as possible.

Easy to fix, but this merge overwrote the change in https://github.com/acm-chil/acm-chil-website/pull/56. I'll open a pull request!

**Comment by tompollard** [comment]
Authors for the tutorial added back in https://github.com/acm-chil/acm-chil-website/pull/57

**Comment by corcra** [comment]
Ah sorry, I didn't manually check the diff closely enough - I thought the only change was adding the rocketchat_id column.

**Comment by tompollard** [comment]
@corcra no problem, glad you merged because I couldn't work out how best to handle it. Not straightforward to resolve conflicts on CSVs!

**Pull request merged**
